### ISSUE TITLE
"User-Agent" header should not be set in browser envs

### ISSUE THREAD

**Issue by atanasbozhkov** [guildxyz/guild-sdk#17]
### Bug Description: 

In the Axios headers for the project - [there's a setting](https://github.com/agoraxyz/guild-sdk/blob/main/src/common.ts#L5) for `User-Agent`. 
This should work in Node environments - but in the browser it results in: 

```
xhr.js:146 Refused to set unsafe header "User-Agent"
```

### Steps to reproduce 
1. Start a new Create-React-App project with typescript 
2. Install `"@guildxyz/sdk": "^1.1.1",`
3. Make a call to the API.

### Temporary workaround
I was able to get around the issue by monkey patching the globals
```
import { globals } from "@guildxyz/sdk/build/src/common";
export const patchGuildSdk = () => {
  if (globals.headers['User-Agent']) {
    delete globals.headers["User-Agent"];
  }
};
```

### Suggested Solution
Can someone share a bit more context around why the `User-Agent` is being set?
Would it be okay if we change it to detect browser environments (via the window object for example) and conditionally set it?

I'm more than happy to raise a PR after we reach a conclusion.

**Comment by cs-balazs** [comment]
Hi @atanasbozhkov, thanks for the report!
In our new `2.0.0` release, the `User-Agent` is no longer being overwritten!
