### ISSUE TITLE
Incorrect typing: guild.role.requirement.getAll

### ISSUE THREAD

**Issue by jackkru69** [guildxyz/guild-sdk#20]
"@guildxyz/sdk": "^2.0.0-rc.7"

https://github.com/agoraxyz/guild-sdk/blob/c6e29965d7a80034a4028ba8049ee2f5735b7251/src/clients/requirement.ts#L22C32-L22C32

Incorrect typing, the function returns Requirement[], and in typing returns Requirement

**Comment by cs-balazs** [comment]
Thanks for the report @jackkru69! I believe this has been fixed in our `2.0.0` release!
