### ISSUE TITLE
GetGuildByIdResponse type doesn't have `admins` property

### ISSUE THREAD

**Issue by KevinLu** [guildxyz/guild-sdk#8]
Despite `/v1/guild/:id` returning an `admins` property in the response, this property does not exist on type `GetGuildByIdResponse`.

Example:
GET `https://api.guild.xyz/v1/guild/our-guild`

Response:
```javascript
{
   admins: [
     0: {id: 45, address: "0xaf17d2da0ccfc4382ba48554be601f28903d3eda", isOwner: false}
     1: {id: 113, address: "0x6c6541cc3ec6bfc2d7b0ca48ccb0225cbbea9b59", isOwner: true}
     2: {id: 12284, address: "0xa65eef5d0566ef2ed242d8719111e3116333278d", isOwner: false}
  ],
  createdAt: "2022-02-14T20:33:40.876+00:00",
  description: "",
  hideFromExplorer: false,
  id: 1985,
  ...
}
```

**Comment by rulfo71** [comment]
Same is happening to me when using `.get(guildIdOrUrlName: string | number)` 

i use to call `https://api.guild.xyz/v1/guild/${guildId}` and get an array of admins and with the`guildClient.guild.get(guildIdOrUrlName)` it's not returning admins. 

is this going to be added to de v2 sdk?

**Comment by rulfo71** [comment]
same for `guildPlatforms`, it's not being returned on `v2`
