### ISSUE TITLE
Add an option to the guild.join method to select platform

### ISSUE THREAD

**Issue by KevinLu** [guildxyz/guild-sdk#9]
Currently, only the `guildId` can be passed to the `guild.join` method, as seen here:
https://github.com/agoraxyz/guild-sdk/blob/66120a1bcbb6bc1b257e1dde490fd4d10328fa65/src/client.ts#L156-L175

However, this won't return the `inviteLink` and `alreadyJoined` properties as specified by the type `JoinResponse`:
https://github.com/agoraxyz/guild-sdk/blob/66120a1bcbb6bc1b257e1dde490fd4d10328fa65/src/types.ts#L8-L11

Can `platform` and `platformUserId` be added to `guild.join`? For example, this is a valid `payload`:
```javascript
{
  guildId: 481
  platform: "DISCORD"
  platformUserId: "965726448839163915"
}
```

**Comment by ejayxyz** [comment]
Thanks for these issues and reports! Currently, we are refactoring and modularize our backend, and the SDK will change in a few ways. We should wait until those changes are live, then after that we will check back to these issues.

**Comment by ejayxyz** [comment]
@KevinLu I would say, we could finish these changes in 2 weeks or so. A few things will change, but not sure about any related breaking change yet. If you create, or manage anything through the SDK, you might have to refactor a bit as well. We are too early to version these things, I would say, but we will think about it.

**Comment by armandRobled** [comment]
GITHUB-MASTER ArmandoRobled
[transactions_FIFO_Universal-4.xlsx](https://github.com/guildxyz/guild-sdk/files/14151684/transactions_FIFO_Universal-4.xlsx)
